### ISSUE TITLE
Game crashes on load, skyline web browser issue (moved from ARCropolis rep)

### ISSUE THREAD

**Issue by sorasin** [skyline-rs/skyline-web#1]
Hi,

Ultimate is crashing on loading unless I disable all Skyline plugins. I have tried updating to no avail. Here is the error:

Thread '<unnamed>' panicked at 'Invalid last url for dialog', C:\Users\Raytwo\.cargo\git\checkouts\skyline-web-b2552367e4749066\bd44c9b\src\dialog.rs:58:18

thank you

**Comment by Raytwo** [comment]
Sorry we kind of missed this issue and I doubt you'll look back here anyway so I'll be closing it.
